### ISSUE TITLE
dns queries not going through clash

### ISSUE THREAD

**Issue by hadifarnoud** [chandelures/luci-app-simple-clash#34]
First of all, thanks for this awesome app. It will make my life easier. I don't have to think about VPNs anymore.

My issue is DNS queries. it doesn't seem like it's going through Clash. All I see are IP addresses in Clash Dashboard connections. How can I force all traffic through Clash?
<img width="734" alt="Screenshot 1401-08-14 at 09 29 22" src="https://user-images.githubusercontent.com/589808/200104966-637f8632-8754-464a-a877-ca1bb0d8bea6.png">

**Comment by chandelures** [comment]
sorry for the late reply, I'm looking for the solution of this issue.

**Comment by chandelures** [comment]
DNS query is going through Clash in my router correctly.

![image](https://user-images.githubusercontent.com/45688491/200456948-b7b4e97a-6c6b-4e2a-bc22-69398a5fc988.png)

It looks like all proxy servers defined in  your configuration have no such as  `udp: true`  segment, then all udp packets will be redirected to `DIRECT` chains. 

you can add `udp: true` in your configuration and try again.

```yaml
proxies:
  - name: "ss1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    udp: true

  - name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol
```
